[project]
name = "stenographer"
version = "0.1.0"
description = "A simple transcription tool using OpenAI's Whisper model."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "requests",
    "ruff",
]

[tool.ruff]
lint.select = [
    "I",  # isort rules for import sorting
    "E",  # pycodestyle errors
    "F",  # Pyflakes
    "C",  # McCabe complexity
]

lint.isort.known-first-party = ["app"]
